language: python
python:
  - "3.5.2"

services:
  - postgresql

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - pip install -r requirements.txt
script:
- ./src/manage.py test api
