# Generated by Django 2.1.2 on 2018-11-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
