# Generated by Django 2.1.2 on 2018-10-31 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randomdata',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='randomdata',
            name='data',
        ),
        migrations.AddField(
            model_name='randomdata',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
